package invoicing.service.global;

import invoicing.Helper.Helper;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Consolidates all per-project Excel files generated by the Month service
 * into a single workbook, grouping by sheet name.
 */
public class GlobalService {

	private static final Pattern PROJECT_FILE_PATTERN = Pattern.compile("^(\\d{1,2})_(\\d{4})_(.+)\\.(xlsx|xls)$", Pattern.CASE_INSENSITIVE);

	public File generateGlobalMonthWorkbook(File monthOutputFolder, LocalDateTime now) throws IOException {
		if (monthOutputFolder == null) {
			throw new IllegalArgumentException("monthOutputFolder cannot be null");
		}
		if (!monthOutputFolder.exists() || !monthOutputFolder.isDirectory()) {
			throw new IllegalArgumentException("Month output folder not found or not a directory: " + monthOutputFolder.getAbsolutePath());
		}

		String month = now.format(DateTimeFormatter.ofPattern("MMMM"));
		String year = now.format(DateTimeFormatter.ofPattern("yyyy"));
		String outputFileName = "Global_" + month + "_" + year + ".xlsx";
		File outputFile = new File(monthOutputFolder, outputFileName);

		List<File> inputFiles = listExcelFiles(monthOutputFolder, outputFileName);
		if (inputFiles.isEmpty()) {
			return null;
		}

		try (Workbook globalWorkbook = new XSSFWorkbook()) {
			Map<String, Sheet> globalSheets = new LinkedHashMap<>();
			Map<String, Integer> nextRowBySheet = new HashMap<>();
			Map<String, Double> totalCostBySheet = new HashMap<>();
			Map<String, Integer> costColumnBySheet = new HashMap<>();

			CellStyle projectHeaderStyle = Helper.getHeaderStyle(globalWorkbook);
			CellStyle totalCurrencyStyle = Helper.getFooterCurrencyStyle(globalWorkbook);

			for (File file : inputFiles) {
				String projectName = extractProjectName(file.getName());
				try (FileInputStream fis = new FileInputStream(file);
					 Workbook srcWorkbook = WorkbookFactory.create(fis)) {

					FormulaEvaluator evaluator = srcWorkbook.getCreationHelper().createFormulaEvaluator();
					IdentityHashMap<CellStyle, CellStyle> styleCache = new IdentityHashMap<>();

					for (int si = 0; si < srcWorkbook.getNumberOfSheets(); si++) {
						Sheet srcSheet = srcWorkbook.getSheetAt(si);
						if (srcSheet == null) continue;

						String sheetName = srcSheet.getSheetName();
						Sheet dstSheet = globalSheets.computeIfAbsent(sheetName, name -> globalWorkbook.createSheet(name));

						int startRow = nextRowBySheet.getOrDefault(sheetName, 0);

						int costCol = costColumnBySheet.computeIfAbsent(sheetName, ignored -> findCostColumn(srcSheet));
						if (costCol < 0) {
							costCol = Math.max(0, findLastNonEmptyColumn(srcSheet));
							costColumnBySheet.put(sheetName, costCol);
						}

						// Project separator row (project name)
						Row titleRow = dstSheet.createRow(startRow);
						Cell titleCell = titleRow.createCell(0);
						titleCell.setCellValue(projectName);
						titleCell.setCellStyle(projectHeaderStyle);
						if (costCol > 0) {
							safeAddMergedRegion(dstSheet, new CellRangeAddress(startRow, startRow, 0, costCol));
						}

						int rowOffset = startRow + 1;
						int lastSrcRow = lastNonEmptyRowIndex(srcSheet);

						copySheetContent(srcSheet, dstSheet, rowOffset, globalWorkbook, evaluator, styleCache);
						copyMergedRegions(srcSheet, dstSheet, rowOffset);
						copyColumnWidths(srcSheet, dstSheet);

						Double projectTotalCost = extractTotalCost(srcSheet, costCol, evaluator);
						if (projectTotalCost != null) {
							totalCostBySheet.merge(sheetName, projectTotalCost, Double::sum);
						}

						nextRowBySheet.put(sheetName, rowOffset + (lastSrcRow + 1) + 1); // +1 blank after section
					}
				} catch (Exception e) {
					// Keep going with other files
					System.err.println("GlobalService: Failed to merge file " + file.getAbsolutePath() + ": " + e.getMessage());
				}
			}

			// Add totals at the end of each destination sheet
			for (Map.Entry<String, Sheet> entry : globalSheets.entrySet()) {
				String sheetName = entry.getKey();
				Sheet sheet = entry.getValue();

				int rowIdx = Math.max(nextRowBySheet.getOrDefault(sheetName, 0), sheet.getLastRowNum() + 1);
				rowIdx += 1; // blank

				int costCol = costColumnBySheet.getOrDefault(sheetName, 0);

				Row totalRow = sheet.createRow(rowIdx);
				Cell labelCell = totalRow.createCell(0);
				labelCell.setCellValue("TOTAL COST (ALL PROJECTS)");
				labelCell.setCellStyle(projectHeaderStyle);
				if (costCol > 0) {
					safeAddMergedRegion(sheet, new CellRangeAddress(rowIdx, rowIdx, 0, costCol - 1));
				}

				Cell costCell = totalRow.createCell(costCol);
				costCell.setCellValue(totalCostBySheet.getOrDefault(sheetName, 0.0));
				costCell.setCellStyle(totalCurrencyStyle);

				// Light autosize on key columns
				int maxAuto = Math.min(costCol, 50);
				for (int c = 0; c <= maxAuto; c++) {
					try {
						sheet.autoSizeColumn(c);
					} catch (Exception ignored) {
					}
				}
			}

			Helper.writeWorkbook(globalWorkbook, outputFile.getAbsolutePath());
		}

		return outputFile;
	}

	private static List<File> listExcelFiles(File folder, String excludeFileName) {
		File[] files = folder.listFiles();
		if (files == null) return List.of();

		List<File> results = new ArrayList<>();
		for (File f : files) {
			if (f == null || !f.isFile()) continue;
			if (excludeFileName != null && excludeFileName.equalsIgnoreCase(f.getName())) continue;
			String name = f.getName().toLowerCase(Locale.ROOT);
			if (name.endsWith(".xlsx") || name.endsWith(".xls")) {
				results.add(f);
			}
		}
		results.sort(Comparator.comparing(File::getName, String.CASE_INSENSITIVE_ORDER));
		return results;
	}

	private static String extractProjectName(String filename) {
		Matcher m = PROJECT_FILE_PATTERN.matcher(filename);
		if (m.matches()) {
			return m.group(3);
		}
		int dot = filename.lastIndexOf('.');
		return dot > 0 ? filename.substring(0, dot) : filename;
	}

	private static int lastNonEmptyRowIndex(Sheet sheet) {
		int last = sheet.getLastRowNum();
		for (int r = last; r >= 0; r--) {
			Row row = sheet.getRow(r);
			if (row == null) continue;
			if (!Helper.isRowEmpty(row)) {
				return r;
			}
		}
		return 0;
	}

	private static int findCostColumn(Sheet sheet) {
		Row header = sheet.getRow(0);
		if (header == null) return -1;
		for (int c = 0; c < header.getLastCellNum(); c++) {
			Cell cell = header.getCell(c, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
			if (cell == null) continue;
			if (cell.getCellType() == CellType.STRING) {
				String v = cell.getStringCellValue();
				if (v != null && v.trim().toLowerCase(Locale.ROOT).startsWith("cost")) {
					return c;
				}
			}
		}
		return -1;
	}

	private static int findLastNonEmptyColumn(Sheet sheet) {
		int lastRow = lastNonEmptyRowIndex(sheet);
		Row row = sheet.getRow(lastRow);
		if (row == null) return 0;
		return Math.max(0, row.getLastCellNum() - 1);
	}

	private static Double extractTotalCost(Sheet sheet, int costCol, FormulaEvaluator evaluator) {
		int lastRow = lastNonEmptyRowIndex(sheet);
		Row totalRow = sheet.getRow(lastRow);
		if (totalRow == null) return null;
		Cell cell = totalRow.getCell(costCol, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
		if (cell == null) return null;
		return getNumericValue(cell, evaluator);
	}

	private static Double getNumericValue(Cell cell, FormulaEvaluator evaluator) {
		if (cell == null) return null;
		try {
			if (cell.getCellType() == CellType.NUMERIC) {
				return cell.getNumericCellValue();
			}
			if (cell.getCellType() == CellType.FORMULA && evaluator != null) {
				CellValue cv = evaluator.evaluate(cell);
				if (cv != null && cv.getCellType() == CellType.NUMERIC) {
					return cv.getNumberValue();
				}
			}
		} catch (Exception ignored) {
		}
		return null;
	}

	private static void copyColumnWidths(Sheet src, Sheet dst) {
		if (src == null || dst == null) return;
		int maxCol = findLastNonEmptyColumn(src);
		for (int c = 0; c <= maxCol; c++) {
			try {
				int srcWidth = src.getColumnWidth(c);
				int dstWidth = dst.getColumnWidth(c);
				if (srcWidth > dstWidth) {
					dst.setColumnWidth(c, srcWidth);
				}
			} catch (Exception ignored) {
			}
		}
	}

	private static void copyMergedRegions(Sheet src, Sheet dst, int rowOffset) {
		if (src == null || dst == null) return;
		for (int i = 0; i < src.getNumMergedRegions(); i++) {
			CellRangeAddress region = src.getMergedRegion(i);
			if (region == null) continue;
			CellRangeAddress shifted = new CellRangeAddress(
					region.getFirstRow() + rowOffset,
					region.getLastRow() + rowOffset,
					region.getFirstColumn(),
					region.getLastColumn()
			);
			safeAddMergedRegion(dst, shifted);
		}
	}

	private static void safeAddMergedRegion(Sheet sheet, CellRangeAddress region) {
		try {
			sheet.addMergedRegion(region);
		} catch (Exception ignored) {
		}
	}

	private static void copySheetContent(
			Sheet srcSheet,
			Sheet dstSheet,
			int rowOffset,
			Workbook dstWorkbook,
			FormulaEvaluator evaluator,
			IdentityHashMap<CellStyle, CellStyle> styleCache
	) {
		int lastRow = lastNonEmptyRowIndex(srcSheet);
		for (int r = 0; r <= lastRow; r++) {
			Row srcRow = srcSheet.getRow(r);
			Row dstRow = dstSheet.createRow(r + rowOffset);
			if (srcRow == null) {
				continue;
			}
			dstRow.setHeight(srcRow.getHeight());

			short lastCellNum = srcRow.getLastCellNum();
			if (lastCellNum < 0) continue;

			for (int c = 0; c < lastCellNum; c++) {
				Cell srcCell = srcRow.getCell(c, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
				if (srcCell == null) continue;

				Cell dstCell = dstRow.createCell(c);
				copyCellValue(srcCell, dstCell, evaluator);
				copyCellStyle(srcCell, dstCell, dstWorkbook, styleCache);
			}
		}
	}

	private static void copyCellValue(Cell srcCell, Cell dstCell, FormulaEvaluator evaluator) {
		switch (srcCell.getCellType()) {
			case STRING -> dstCell.setCellValue(srcCell.getStringCellValue());
			case NUMERIC -> dstCell.setCellValue(srcCell.getNumericCellValue());
			case BOOLEAN -> dstCell.setCellValue(srcCell.getBooleanCellValue());
			case ERROR -> dstCell.setCellErrorValue(srcCell.getErrorCellValue());
			case FORMULA -> {
				if (evaluator == null) {
					dstCell.setCellValue(srcCell.getCellFormula());
					return;
				}
				CellValue cv;
				try {
					cv = evaluator.evaluate(srcCell);
				} catch (Exception e) {
					cv = null;
				}
				if (cv == null) {
					dstCell.setBlank();
					return;
				}
				switch (cv.getCellType()) {
					case STRING -> dstCell.setCellValue(cv.getStringValue());
					case NUMERIC -> dstCell.setCellValue(cv.getNumberValue());
					case BOOLEAN -> dstCell.setCellValue(cv.getBooleanValue());
					case ERROR -> dstCell.setCellErrorValue(cv.getErrorValue());
					default -> dstCell.setBlank();
				}
			}
			default -> dstCell.setBlank();
		}
	}

	private static void copyCellStyle(
			Cell srcCell,
			Cell dstCell,
			Workbook dstWorkbook,
			IdentityHashMap<CellStyle, CellStyle> styleCache
	) {
		CellStyle srcStyle = srcCell.getCellStyle();
		if (srcStyle == null) return;

		CellStyle cached = styleCache.get(srcStyle);
		if (cached != null) {
			dstCell.setCellStyle(cached);
			return;
		}

		try {
			CellStyle newStyle = dstWorkbook.createCellStyle();
			newStyle.cloneStyleFrom(srcStyle);
			styleCache.put(srcStyle, newStyle);
			dstCell.setCellStyle(newStyle);
		} catch (Exception ignored) {
		}
	}
}
